# change the followings to match your Github username and repo name
baseurl: "/policedata" # the name of your github repo
url: "https://bcdigschol.github.io" # the url of your github pages (change BCDigSchol to your username)

# site information used in page title, meta data etc.
title: "North End Police Data (1854-59)"
description: ILA Summer Internship Project using the Police Ledger from Burns


# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: About
    submenu:
    title: About the project
    link: about
  - title: Interesting Discoveries
    link: interesting_discoveries
  - title: Additional Resources
    link: additional_resources
  - title: Data
    submenu:
      - title: Access the Dataset
        link: data
      - title: Example 1
        link: example1
      - title: Example 2
        link: example2

# sets whether a search bar appears on the site header
search-bar: false

hide-footer: false # set to true to hide the footer
#footer-message: Put Your Footer Message Here | CC BY-NC License
footer-submessage: ILA internship with Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2



